# Generated by Django 2.1.7 on 2019-05-29 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=15)),
                ('number', models.IntegerField()),
                ('date_create_statement', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 29, 10, 14, 16, 970413), null=True)),
                ('status_pass', models.CharField(choices=[('inprocess', 'inprocess'), ('finished', 'finished')], max_length=10)),
            ],
        ),
    ]
